vocat/accounts/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView

from .views import *


urlpatterns = [
    # This assumes that Home URL is '/'
    url(r'^$', RedirectView.as_view(url='/'), name='home'),

    # Registration
    url(r'^registration/$', RegistrationView.as_view(), name='registration'),
    url(r'^registration/done/$', RegistrationDoneView.as_view(), name='registration_done'),

    # Login and Logout
    url(r'^login/$', LoginView.as_view(), name='login'),  # Login(HTML POST) or Obtain Token(JSON POST)
    url(r'^logout/$', LogoutView.as_view(), name='logout'),

    # Password change for logged in users
    url(r'^password_change/$', PasswordChangeView.as_view(), name='password_change'),
    url(r'^password_change/done/$', PasswordChangeDoneView.as_view(), name='password_change_done'),

    # Password reset for anonymous users
    url(r'^password_reset/$', PasswordResetView.as_view(), name='password_reset'),
    url(r'^password_reset/done/$', PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^reset/done/$', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    # UserProfile See/Change
    url(r'^profile/$', UserProfileView.as_view(), name='profile_detail'),
    url(r'^profile_change/$', UserProfileChangeView.as_view(), name='profile_change'),
]

vocat/api/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^users/$', UserList.as_view(), name='user-list'),
    url(r'^users/(?P<pk>[0-9]+)$', UserDetail.as_view(), name='user-detail'),

    url(r'^wordbooks/$', WordBookList.as_view(), name='wordbook-list'),
    url(r'^wordbooks/(?P<pk>[0-9]+)$', WordBookDetail.as_view(), name='wordbook-detail'),
    url(r'^booksections/$', BookSectionList.as_view(), name='booksection-list'),
    url(r'^booksections/(?P<pk>[0-9]+)$', BookSectionDetail.as_view(), name='booksection-detail'),
    url(r'^vocabularies/$', VocabularyList.as_view(), name='vocabulary-list'),
    url(r'^vocabularies/(?P<pk>[0-9]+)$', VocabularyDetail.as_view(), name='vocabulary-detail'),

    # url(r'^tasks/$', TaskList.as_view(), name='task_list'),
    # url(r'^tasks/(?P<pk>[0-9]+)$', TaskDetail.as_view(), name='task_detail'),
]

vocat/testapp/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', Home.as_view(), name='home'),

    url(r'^admin/book_upload', BookUploadView.as_view(), name='book-upload'),

    url(r'^books/$', BookList.as_view(), name='book-list'),
    url(r'^books/(?P<pk>[0-9]+-[0-9]+)/$', BookDetail.as_view(), name='book-detail'),

    url(r'^book-market/$', BookMarketList.as_view(), name='book-market'),
    url(r'^book-market/(?P<pk>[0-9]+-[0-9]+)/$', BookMarketDetail.as_view(), name='book-market-detail'),

    url(r'^sections/$', SectionList.as_view(), name='section-list'),
    url(r'^sections/(?P<pk>[0-9]+-[0-9]+)/$', SectionDetail.as_view(), name='section-detail'),
    url(r'^vocabularies/$', VocabularyList.as_view(), name='vocabulary-list'),
    url(r'^vocabularies/(?P<pk>[0-9]+-[0-9]+)/$', VocabularyDetail.as_view(), name='vocabulary-detail'),

    url(r'^sync/$', SyncList.as_view(), name='sync'),
]

vocat/vocat/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    # For Shark
    url(r'^admin/', admin.site.urls),

    # Accounts (Login, Logout, Registration, Profile, Password Reset, Password Change)
    url(r'^accounts/', include('accounts.urls', namespace='accounts', app_name='accounts')),

    # Main App
    url(r'', include('testapp.urls', namespace='testapp', app_name='testapp')),

    # Test
    url(r'^api/', include('api.urls', namespace='api', app_name='url')),

]

vocat/testapp/forms.py
from django import forms
from .models import Book


class BookCreationForm(forms.ModelForm):

    class Meta:
        model = Book
        fields = ('language_for', 'language_by', 'title', 'description', 'is_public')

vocat/testapp/views.py
from django.views.generic import View
from django.template.response import TemplateResponse
from rest_framework.parsers import FileUploadParser
from rest_framework import generics, filters
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated, IsAdminUser, BasePermission, SAFE_METHODS
from .serializers import *
from .models import *
from .forms import BookCreationForm

import csv, codecs


class Home(View):
    template_anonymous = 'testapp/home.html'
    template_mainapp = 'testapp/home_mainapp.html'

    def get(self, request):
        if request.user.is_authenticated():
            return self.show_home_mainapp()
        return self.show_home_anonymous()

    def show_home_anonymous(self):
        data = User.objects.all().count()
        context = {
        #     'title': _('Profile'),
            'data': data,
        }
        return TemplateResponse(self.request, self.template_anonymous, context)

    def show_home_mainapp(self):
        context = {
            # 'title': _('Profile'),
            # 'data': data,
        }
        return TemplateResponse(self.request, self.template_mainapp, context)


class IsBookOwnerOrPublicReadOnly(BasePermission):
    def has_object_permission(self, request, view, obj):
        # If request is GET, HEAD or OPTION
        if request.method in SAFE_METHODS:
            # you can GET any public book or book of your own.
            return obj.is_public or obj.owner == request.user
        # If request is PUT, PATCH, DELETE, you must be the owner.
        return obj.owner == request.user


class IsSectionOwnerOrPublicReadOnly(BasePermission):
    def has_object_permission(self, request, view, obj):
        # If request is GET, HEAD or OPTION
        if request.method in SAFE_METHODS:
            # you can GET any public book or book of your own.
            return obj.book.is_public or obj.book.owner == request.user
        # If request is PUT, PATCH, DELETE, you must be the owner.
        return obj.book.owner == request.user


class IsVocabularyOwnerOrPublicReadOnly(BasePermission):
    def has_object_permission(self, request, view, obj):
        # If request is GET, HEAD or OPTION
        if request.method in SAFE_METHODS:
            # you can GET any public book or book of your own.
            return obj.section.book.is_public or obj.section.book.owner == request.user
        # If request is PUT, PATCH, DELETE, you must be the owner.
        return obj.section.book.owner == request.user


class BookUploadView(generics.GenericAPIView):
    permission_classes = (IsAdminUser,)
    template_name = 'testapp/book_upload.html'

    book_creation_form = BookCreationForm

    def get(self, request):
        context = {'form': self.book_creation_form}
        return TemplateResponse(self.request, self.template_name, context)

    def post(self, request):
        if not request.FILES:
            return Response(status=400)
        file_obj = request.FILES['file']
        book = Book.objects.create(id='0', owner=request.user, creator=request.user,
                                   is_public=request.POST.get('is_public', False),
                                   language_for=request.POST['language_for'], language_by=request.POST['language_by'],
                                   title=request.POST['title'], description=request.POST['description'])

        reader = csv.DictReader(file_obj)
        s_sort, v_sort = 1, 1
        for row in reader:
            print 'Creating - ', row['vocabulary']
            try:
                section = Section.objects.get(book__exact=book, title=row['section'], sort=s_sort-1)
            except Section.DoesNotExist:
                if row['section'] is None or row['section'] == '':
                    section = Section.objects.get(book__exact=book, type=0)
                else:
                    section = Section.objects.create(id='0', book=book, sort=s_sort, title=row['section'])
                s_sort += 1
                v_sort = 1
            if row['vocabulary'] is not None and row['vocabulary'] != '':
                Vocabulary.objects.create(id='0', section=section, sort=v_sort, name=row['vocabulary'],
                                          meaning=row['meaning'])
                v_sort += 1
        return Response(status=200)


class BookList(generics.ListCreateAPIView):
    """
    GET: Return a list of user-owned books (if authenticated).
    POST: Create & return a user-owned book (if authenticated).
    """
    serializer_class = BookSerializer
    permission_classes = (IsAuthenticated,)
    template_name = 'testapp/books.html'
    # pagination_class = LargeResultsSetPagination

    def get_queryset(self):
        user = self.request.user
        books = user.owned_books.all()
        return books

    def get(self, request, *args, **kwargs):
        serializer = self.get_serializer(self.get_queryset(), many=True)
        data = serializer.data
        if request.accepted_renderer.format == 'html':
            data = {'data': data}
            return Response(data, template_name=self.template_name)

        return Response(data)


class BookDetail(generics.RetrieveUpdateDestroyAPIView):
    """
    GET: Return Book detail (if authenticated).
    PUT: Create & return Book detail (if authenticated).
    PATCH: Update Book detail (if authenticated and owner).
    DELETE: Delete Book (if authenticated and owner).
    """
    queryset = Book.objects.all()
    serializer_class = BookSerializer
    permission_classes = (IsAuthenticated, IsBookOwnerOrPublicReadOnly)


class SectionList(generics.ListCreateAPIView):
    """
    GET: Return a list of user-owned sections (if authenticated).
    POST: Create & return a user-owned section (if authenticated).
    """
    serializer_class = SectionSerializer
    permission_classes = (IsAuthenticated,)
    # template_name = 'testapp/books.html'
    # pagination_class = LargeResultsSetPagination

    def get_queryset(self):
        user = self.request.user
        sections = Section.objects.filter(book__owner__exact=user)
        return sections

    def get(self, request, *args, **kwargs):
        serializer = self.get_serializer(self.get_queryset(), many=True)
        data = serializer.data
        # if request.accepted_renderer.format == 'html':
        #     data = {'data': data}
        #     return Response(data, template_name=self.template_name)

        return Response(data)


class SectionDetail(generics.RetrieveUpdateDestroyAPIView):
    """
    GET: Return Section detail (if authenticated).
    PUT: Create & return Section detail (if authenticated).
    PATCH: Update Section detail (if authenticated and owner).
    DELETE: Delete Section (if authenticated and owner).
    """
    queryset = Section.objects.all()
    serializer_class = SectionSerializer
    permission_classes = (IsAuthenticated, IsSectionOwnerOrPublicReadOnly)


class VocabularyList(generics.ListCreateAPIView):
    """
    GET: Return a list of user-owned vocabularies (if authenticated).
    POST: Create & return a user-owned vocabularies (if authenticated).
    """
    serializer_class = VocabularySerializer
    permission_classes = (IsAuthenticated,)
    # template_name = 'testapp/books.html'
    # pagination_class = LargeResultsSetPagination

    def get_queryset(self):
        user = self.request.user
        vocabularies = Vocabulary.objects.filter(section__book__owner__exact=user)
        return vocabularies

    def get(self, request, *args, **kwargs):
        serializer = self.get_serializer(self.get_queryset(), many=True)
        data = serializer.data
        # if request.accepted_renderer.format == 'html':
        #     data = {'data': data}
        #     return Response(data, template_name=self.template_name)

        return Response(data)


class VocabularyDetail(generics.RetrieveUpdateDestroyAPIView):
    """
    GET: Return Vocabulary detail (if authenticated).
    PUT: Create & return Vocabulary detail (if authenticated).
    PATCH: Update Vocabulary detail (if authenticated and owner).
    DELETE: Delete Vocabulary (if authenticated and owner).
    """
    queryset = Vocabulary.objects.all()
    serializer_class = VocabularySerializer
    permission_classes = (IsAuthenticated, IsVocabularyOwnerOrPublicReadOnly)


class BookMarketList(generics.ListCreateAPIView):
    """
    GET: Return a list of public books.
    POST: Create & return a user-owned public book.
    """
    serializer_class = BookSerializer
    permission_classes = (IsAuthenticated,)
    template_name = 'testapp/book_market.html'
    # pagination_class = LargeResultsSetPagination

    def get_queryset(self):
        books = Book.objects.filter(is_public=True)
        return books

    def get(self, request, *args, **kwargs):
        serializer = self.get_serializer(self.get_queryset(), many=True)
        data = serializer.data
        if request.accepted_renderer.format == 'html':
            data = {'data': data}
            return Response(data, template_name=self.template_name)
        return Response(data)


class BookMarketDetail(generics.RetrieveAPIView):
    queryset = Book.objects.filter(is_public=True)
    serializer_class = BookDownloadSerializer
    permission_classes = (IsAuthenticated,)


class SyncList(generics.ListCreateAPIView):
    serializer_class = BookDownloadSerializer
    permission_classes = (IsAuthenticated,)

    def get_queryset(self):
        user = self.request.user
        books = user.owned_books.all()
        return books

vocat/testapp/templates/testapp/base_mainapp.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Base
{% endblock %}

{% block css %}
<link href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en" rel="stylesheet">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link rel="stylesheet" href="{% static 'common/mdl/material.min.css' %}">
<link rel="stylesheet" href="{% static 'testapp/css/base_mainapp.css' %}">
<link rel="stylesheet" href="{% static 'common/vocat/css/vocat_color.css' %}">
{% endblock %}

{% block body %}
<div class="demo-layout mdl-layout mdl-js-layout mdl-layout--fixed-drawer mdl-layout--fixed-header">
  <header class="demo-header mdl-layout__header vocat-bg--primary">
    <div class="mdl-layout__header-row">
      <div class="mdl-layout-title">
        <img src="{% static 'common/vocat/img/logo_light_notext.png' %}" width="21" height="21"/>
        {% block title_menu %}{% endblock %}
      </div>
      <div class="mdl-layout-spacer"></div>
      <div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable">
        <label class="mdl-button mdl-js-button mdl-button--icon" for="search">
          <i class="material-icons">search</i>
        </label>
        <div class="mdl-textfield__expandable-holder">
          <input class="mdl-textfield__input" type="text" id="search">
          <label class="mdl-textfield__label" for="search">Enter your query...</label>
        </div>
      </div>
      <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon" id="hdrbtn">
        <i class="material-icons">more_vert</i>
      </button>
      <ul class="mdl-menu mdl-js-menu mdl-js-ripple-effect mdl-menu--bottom-right" for="hdrbtn">
        <li class="mdl-menu__item">About</li>
        <li class="mdl-menu__item">Contact</li>
        <li class="mdl-menu__item">Legal information</li>
      </ul>
    </div>
  </header>
  <div class="demo-drawer mdl-layout__drawer mdl-color--blue-grey-900 mdl-color-text--blue-grey-50">
    <header class="demo-drawer-header">
      <img src="{% static 'testapp/img/ic_user.png' %}" class="demo-avatar">
      <div><span>{{ request.user.name }}</span></div>
      <div class="demo-avatar-dropdown">
        <span>{{ request.user.email }}</span>
        <div class="mdl-layout-spacer"></div>
        <button id="accbtn" class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon">
          <i class="material-icons" role="presentation">arrow_drop_down</i>
          <span class="visuallyhidden">Accounts</span>
        </button>
        <div class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect" for="accbtn">
          <a class="mdl-menu__item" href="{% url 'accounts:profile_detail' %}">Profile</a>
          <a class="mdl-menu__item" href="{% url 'accounts:logout' %}">Logout</a>
          <a class="mdl-menu__item"><i class="material-icons">add</i>Add another account...</a>
        </div>
      </div>
    </header>
    <nav class="demo-navigation mdl-navigation mdl-color--white">
      <a class="mdl-navigation__link {% if request.resolver_match.url_name == "home" %}active{% endif %}" href="{% url 'testapp:home' %}"><i class="material-icons" role="presentation">home</i>홈</a>
      <a class="mdl-navigation__link {% if request.resolver_match.url_name == "knowhow_feed" %}active{% endif %}" href=""><i class="material-icons" role="presentation">inbox</i>노하우 피드</a>
      <a class="mdl-navigation__link" href=""><i class="material-icons" role="presentation">delete</i>스터디</a>
      <a class="mdl-navigation__link {% if request.resolver_match.url_name == "book-list" %}active{% endif %}" href="{% url 'testapp:book-list' %}"><i class="material-icons" role="presentation">report</i>단어책</a>
      <a class="mdl-navigation__link {% if request.resolver_match.url_name == "book-market" %}active{% endif %}" href="{% url 'testapp:book-market' %}"><i class="material-icons" role="presentation">forum</i>북마켓</a>
      <a class="mdl-navigation__link" href=""><i class="material-icons" role="presentation">flag</i>Account</a>
      <a class="mdl-navigation__link" href=""><i class="material-icons" role="presentation">local_offer</i>Settings</a>
      <a class="mdl-navigation__link" href=""><i class="material-icons" role="presentation">shopping_cart</i>Send feedback</a>
      <a class="mdl-navigation__link" href=""><i class="material-icons" role="presentation">people</i>Social</a>
      <div class="mdl-layout-spacer"></div>
    </nav>
    <div class="legal mdl-color--white">
      <p class="copyright">Vocat ©</p>
      <a href="/">Privacy</a> &amp; <a href="/">Terms</a>
    </div>
  </div>
  <main class="mdl-layout__content mdl-color--grey-100">
    {% block content %}
    {% endblock %}
  </main>
</div>

{% endblock %}

{% block js %}
<script src="{% static 'common/mdl/material.min.js' %}"></script>
<script src="{% static 'common/jquery/jquery-1.12.0.min.js' %}"></script>
{% block js2 %}
{% endblock %}
{% endblock %}

vocat/testapp/templates/testapp/book_market.html
{% extends 'testapp/base_mainapp.html' %}
{% load staticfiles %}
{% load humanize %}

{% block title %}북마켓{% endblock %}
{% block title_menu %}북마켓{% endblock %}



{% block content %}
<div style="max-width:900px; margin:0 auto; padding:60px 10px;">
  <h4>북마켓에 올라 온 책</h4>
  <div style="margin-bottom:5px; text-align:right;">
    <a id="tt1" class="mdl-button mdl-js-button mdl-button--raised mdl-button--accent">
      책 올리기
    </a>
    <div class="mdl-tooltip" for="tt1">내 단어 책을 공유할 수 있습니다.</div>
  </div>
  <table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp" style="width:100%;">
    <colgroup>
      <col span="1" style="width:65%;">
      <col span="1" style="width:5%;">
      <col span="1" style="width:10%;">
      <col span="1" style="width:5%;">
      <col span="1" style="width:5%;">
      <col span="1" style="width:5%;">
      <col span="1" style="width:5%;">
    </colgroup>
    <thead>
      <tr>
        <th class="mdl-data-table__cell--non-numeric">책 이름</th>
        <th>단어</th>
        <th class="mdl-data-table__cell--non-numeric">만든이</th>
        <th>추천</th>
        <th>비추천</th>
        <th class="mdl-data-table__cell--non-numeric">날짜</th>
        <th class="mdl-data-table__cell--non-numeric">메뉴</th>
      </tr>
    </thead>
    <tbody>
      {% for book in data %}
      <tr>
        <td class="mdl-data-table__cell--non-numeric">{{ book.title }}</td>
        <td>{{ book.vocab_count }}</td>
        <td class="mdl-data-table__cell--non-numeric">{{ book.creator.name }}</td>
        <td>{{ book.likes|length }}</td>
        <td>{{ book.dislikes|length }}</td>
        <td class="mdl-data-table__cell--non-numeric">{{ book.date_created|naturalday }}</td>
        <td class="mdl-data-table__cell--non-numeric">
          <button id="book-{{ book.id }}-action"
                  class="mdl-button mdl-js-button mdl-button--icon">
            <i class="material-icons">more_vert</i>
          </button>
          <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect"
              for="book-{{ book.id }}-action">
            <li disabled class="mdl-menu__item">{{ book.title }}</li>
            <li class="mdl-menu__item" onclick="getBook({{ book.id }})">보기</li>
            <li class="mdl-menu__item">수정</li>
            <li class="mdl-menu__item" onclick="deleteBook({{ book.id }}, '{{ book.title }}')">삭제</li>
          </ul>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

vocat/testapp/templates/testapp/book_upload.html
{% extends 'base.html' %}

{% block body %}

<form action="{{ app_path }}" method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}
    <input id="file" name="file" type="file" accept=".csv" /> <br><br>
    <input type="submit" />
</form>

{% endblock %}

vocat/testapp/templates/testapp/home.html
{% extends 'base_home.html' %}
{% load staticfiles %}
{% load humanize %}

{% block title %}Home{% endblock %}


{% block content %}
  <!-- Wide card with share menu button -->
  <style>
    .demo-card-wide.mdl-card {
      width: 100%;
    }
    .demo-card-wide > .mdl-card__title {
      color: #000;
      height: 60px;
      border-bottom: 1px solid #e5e5e5;
    }
    .demo-card-wide > .mdl-card__menu {
      color: #fff;
    }
  </style>

  <div style="max-width:600px; margin:0 auto; padding:60px 10px;">
    <div class="demo-card-wide mdl-card mdl-shadow--2dp">
      <div class="mdl-card__title">
        <h2 class="mdl-card__title-text">vocat</h2>
      </div>
      <div class="mdl-card__supporting-text">
        n. 심플하고 강력한 단어암기 앱<br><br>
        예문<br>
        Sign in or register to vocat.<br>
        보캣에 <a href="{% url 'accounts:login' %}">로그인</a> 하거나 <a href="{% url 'accounts:registration' %}">회원가입</a>하세요.<br><br>
        {{ data|intcomma }} people are using vocat already.<br>
        이미 <a>{{ data|intcomma }}명</a>이 보캣을 사용하고 있습니다.<br><br>
        Vocat is also available on Google Play Store.<br>
        보캣은 <a>구글 플레이스토어</a>에서도 만나볼 수 있습니다.
      </div>
      <div class="mdl-card__actions mdl-card--border">

        <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">
          보캣에 대해서 자세히 알아보기
        </a>
      </div>
      <div class="mdl-card__menu">
        <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect">
          <i class="material-icons">share</i>
        </button>
        <div class="fb-like" data-href="https://www.facebook.com/vocatapp/" data-layout="button_count" data-action="like" data-show-faces="false" data-share="false"></div>
      </div>
    </div>
  </div>
{% endblock %}

vocat/testapp/templates/testapp/home_mainapp.html
{% extends 'testapp/base_mainapp.html' %}
{% load staticfiles %}
{% block title %}Home{% endblock %}
{% block title_menu %}Home{% endblock %}



{% block content %}
hello main app
{% endblock %}