vocat/accounts/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView

from .views import *


urlpatterns = [
    # This assumes that Home URL is '/'
    url(r'^$', RedirectView.as_view(url='/'), name='home'),

    # Registration
    url(r'^registration/$', RegistrationView.as_view(), name='registration'),
    url(r'^registration/done/$', RegistrationDoneView.as_view(), name='registration_done'),

    # Login and Logout
    url(r'^login/$', LoginView.as_view(), name='login'),  # Login(HTML POST) or Obtain Token(JSON POST)
    url(r'^logout/$', LogoutView.as_view(), name='logout'),

    # Password change for logged in users
    url(r'^password_change/$', PasswordChangeView.as_view(), name='password_change'),
    url(r'^password_change/done/$', PasswordChangeDoneView.as_view(), name='password_change_done'),

    # Password reset for anonymous users
    url(r'^password_reset/$', PasswordResetView.as_view(), name='password_reset'),
    url(r'^password_reset/done/$', PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^reset/done/$', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    # UserProfile See/Change
    url(r'^profile/$', UserProfileView.as_view(), name='profile_detail'),
    url(r'^profile_change/$', UserProfileChangeView.as_view(), name='profile_change'),
]

vocat/api/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^users/$', UserList.as_view(), name='user-list'),
    url(r'^users/(?P<pk>[0-9]+)$', UserDetail.as_view(), name='user-detail'),

    url(r'^wordbooks/$', WordBookList.as_view(), name='wordbook-list'),
    url(r'^wordbooks/(?P<pk>[0-9]+)$', WordBookDetail.as_view(), name='wordbook-detail'),
    url(r'^booksections/$', BookSectionList.as_view(), name='booksection-list'),
    url(r'^booksections/(?P<pk>[0-9]+)$', BookSectionDetail.as_view(), name='booksection-detail'),
    url(r'^vocabularies/$', VocabularyList.as_view(), name='vocabulary-list'),
    url(r'^vocabularies/(?P<pk>[0-9]+)$', VocabularyDetail.as_view(), name='vocabulary-detail'),

    # url(r'^tasks/$', TaskList.as_view(), name='task_list'),
    # url(r'^tasks/(?P<pk>[0-9]+)$', TaskDetail.as_view(), name='task_detail'),
]

vocat/rest_auth/registration/urls.py
from django.views.generic import TemplateView
from django.conf.urls import patterns, url

from .views import RegisterView, VerifyEmailView

urlpatterns = patterns(
    '',
    url(r'^$', RegisterView.as_view(), name='rest_register'),
    url(r'^verify-email/$', VerifyEmailView.as_view(), name='rest_verify_email'),

    # This url is used by django-allauth and empty TemplateView is
    # defined just to allow reverse() call inside app, for example when email
    # with verification link is being sent, then it's required to render email
    # content.

    # account_confirm_email - You should override this view to handle it in
    # your API client somehow and then, send post to /verify-email/ endpoint
    # with proper key.
    # If you don't want to use API on that step, then just use ConfirmEmailView
    # view from:
    # djang-allauth https://github.com/pennersr/django-allauth/blob/master/allauth/account/views.py#L190
    url(r'^account-confirm-email/(?P<key>\w+)/$', TemplateView.as_view(),
        name='account_confirm_email'),
)

vocat/vocat/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    # For Shark
    url(r'^admin/', admin.site.urls),

    # Accounts (Login, Logout, Registration, Profile, Password Reset, Password Change)
    url(r'^accounts/', include('accounts.urls', namespace='accounts', app_name='accounts')),

    # Main App
    url(r'', include('testapp.urls', namespace='testapp', app_name='testapp')),

    # Test
    url(r'^api/', include('api.urls', namespace='api', app_name='url')),

]

vocat/accounts/models.py
# -- coding: utf-8 --
from __future__ import unicode_literals

import re
import uuid
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.core import validators
from django.core.mail import send_mail
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone

from common.db_choices import SEX_CHOICES, LANGUAGE_CHOICES, DEVICE_TYPES


name_regex = re.compile(r"^[\w\s.'-]+$", re.U)


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, name, password, **extra_fields):
        """
        Creates and saves a User with the given username, email and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        if not name:
            raise ValueError('The given name must be set')
        email = self.normalize_email(email)
        name = self.normalize_name(name)
        user = self.model(email=email, name=name, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, name, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, name, password, **extra_fields)

    def create_superuser(self, email, name, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, name, password, **extra_fields)

    @staticmethod
    def normalize_name(name):
        name = name or ''
        name = " ".join(name.split())
        return name


class User(AbstractBaseUser, PermissionsMixin):
    """
    An abstract base class implementing a fully featured User model with
    admin-compliant permissions.

    Username and password are required. Other fields are optional.
    """
    email = models.EmailField(
        _('email address'),
        max_length=255,
        unique=True,
        help_text=_('Required. Valid email address.'),
        error_messages={
            'unique': _("A user with that email already exists."),
        },
    )
    name = models.CharField(
        _('name'),
        max_length=70,
        help_text=_("Required. 70 characters or fewer. Characters, numbers "
                    "hyphens(-), apostrophes(') dots(.) and single spaces only."),
        validators=[
            validators.RegexValidator(
                name_regex,
                _("Enter a valid username. This value may contain only "
                  "characters, numbers, hyphens(-), apostrophes(') "
                  "dots(.) and single spaces."),
            ),
        ],
    )
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(
            _('date joined'), default=timezone.now)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name']

    def get_full_name(self):
        return self.name

    def get_short_name(self):
        return self.name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """
        Sends an email to this User.
        """
        send_mail(subject, message, from_email, [self.email], **kwargs)


class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='profile', on_delete=models.CASCADE)
    sex = models.CharField(max_length=1, choices=SEX_CHOICES, blank=True)
    date_of_birth = models.DateField(null=True, blank=True)
    language_for = models.CharField(max_length=2, choices=LANGUAGE_CHOICES, default='EN')
    language_by = models.CharField(max_length=2, choices=LANGUAGE_CHOICES, default='KO')


class Device(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, related_name='devices', on_delete=models.CASCADE)
    type = models.IntegerField(choices=DEVICE_TYPES, default=0)


class AutoBookCount(models.Model):
    user = models.OneToOneField(User, related_name='auto_book_count', on_delete=models.CASCADE)
    count = models.IntegerField(default=0)


class AutoSectionCount(models.Model):
    user = models.OneToOneField(User, related_name='auto_section_count', on_delete=models.CASCADE)
    count = models.IntegerField(default=0)


class AutoVocabularyCount(models.Model):
    user = models.OneToOneField(User, related_name='auto_vocabulary_count', on_delete=models.CASCADE)
    count = models.IntegerField(default=0)


def create_user_stuff(sender, instance, created, **kwargs):
    """ Create a user profile when a new user account is created """
    if created:
        UserProfile.objects.create(user=instance)
        Device.objects.create(user=instance)
        AutoBookCount.objects.create(user=instance)
        AutoSectionCount.objects.create(user=instance)
        AutoVocabularyCount.objects.create(user=instance)

post_save.connect(create_user_stuff, sender=User)

vocat/accounts/forms.py
from django.contrib.auth.forms import (
    UserCreationForm as BaseCreationForm,
    UserChangeForm as BaseChangeForm
)
from django import forms

from .models import User, UserProfile


class UserCreationForm(BaseCreationForm):
    """
    A form that creates a user, with no privileges, from the given email and
    password.
    """
    # name = forms.CharField(max_length=70)

    def __init__(self, *args, **kargs):
        super(UserCreationForm, self).__init__(*args, **kargs)

    class Meta:
        model = User
        fields = ('email', 'name',)


class UserChangeForm(BaseChangeForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    def __init__(self, *args, **kargs):
        super(UserChangeForm, self).__init__(*args, **kargs)

    class Meta:
        model = User
        fields = '__all__'


class UserProfileChangeForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        exclude = ('user',)

vocat/accounts/templates/accounts/logged_out.html
{% extends 'base_home.html' %}
{% load staticfiles %}
{% load i18n admin_static %}
{% block title %}Logged out{% endblock %}


{% block content %}
  <!-- Wide card with share menu button -->
  <style>
    .demo-card-wide.mdl-card {
      width: 100%;
    }
    .demo-card-wide > .mdl-card__title {
      color: #000;
      height: 60px;
      border-bottom: 1px solid #e5e5e5;
    }
    .demo-card-wide > .mdl-card__menu {
      color: #fff;
    }
  </style>

  <div style="max-width:400px; margin:0 auto; padding:60px 10px;">
    <div class="demo-card-wide mdl-card mdl-shadow--2dp">
      <div class="mdl-card__title">
        <h2 class="mdl-card__title-text">로그아웃</h2>
      </div>
      <div class="mdl-card__supporting-text" style="text-align:center;">
        <a href="{% url 'accounts:home' %}">홈으로</a>
        <p>보캣과 함께해 주셔서 감사합니다.</p>
        <p>{% trans "Thanks for spending some quality time with vocat today." %}</p>
        <p><a href="{% url 'accounts:login' %}">다시 로그인 하기</a></p>
      </div>
      <div class="mdl-card__actions mdl-card--border">
        <a class="mdl-button mdl-js-button vocat-color--primary" href="{% url 'accounts:login' %}" style="float:right;">
          다시 로그인하기
        </a>
      </div>
      <div class="mdl-card__menu">
        <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect">
          <i class="material-icons">share</i>
        </button>
        <div class="fb-like" data-href="https://www.facebook.com/vocatapp/" data-layout="button_count" data-action="like" data-show-faces="false" data-share="false"></div>
      </div>
    </div>
  </div>

{% endblock %}

vocat/accounts/templates/accounts/login.html
{% extends 'base_home.html' %}
{% load staticfiles %}
{% load i18n admin_static %}
{% block title %}Login{% endblock %}


{% block content %}
  <!-- Wide card with share menu button -->
  <style>
    .demo-card-wide.mdl-card {
      width: 100%;
    }
    .demo-card-wide > .mdl-card__title {
      color: #000;
      height: 60px;
      border-bottom: 1px solid #e5e5e5;
    }
    .demo-card-wide > .mdl-card__menu {
      color: #fff;
    }
  </style>

  <div style="max-width:400px; margin:0 auto; padding:60px 10px;">
    <form action="{{ app_path }}" method="post" id="login-form">{% csrf_token %}
      <div class="demo-card-wide mdl-card mdl-shadow--2dp">
        <div class="mdl-card__title">
          <h2 class="mdl-card__title-text">로그인</h2>
        </div>
        <div class="mdl-card__supporting-text" style="text-align:center;">
          {% if form.errors and not form.non_field_errors %}
            <p class="errornote">
              {% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
            </p>
          {% endif %}

          {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
              <p class="errornote">
                {{ error }}
              </p>
            {% endfor %}
          {% endif %}

          <a id="tt1" href="{% url 'accounts:registration' %}" style="color:gray;">가입하기</a> / <a id="tt2" href="{% url 'accounts:password_reset' %}" style="color:gray;">비밀번호 찾기</a>
          <div class="mdl-tooltip" for="tt1">보캣에 가입하기</div>
          <div class="mdl-tooltip" for="tt2">비밀번호 초기화 링크가 갑니다.</div>

          <div id="content-main">
            {% if user.is_authenticated %}
              <p class="errornote">
                {% blocktrans trimmed with username=request.user.username %}
                  You are authenticated as {{ username }}, but are not authorized to
                  access this page. Would you like to login to a different account?
                {% endblocktrans %}
              </p>
            {% endif %}

            {{ form.username.errors }}
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">

              <input id="id_username" maxlength="254" name="username" type="email" class="mdl-textfield__input">
              <label class="mdl-textfield__label" for="id_username">이메일 주소</label>
            </div>
            {{ form.password.errors }}
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
              <input id="id_password" pattern=".{0}|.{8,}" title="최소 8 글자" name="password" type="password"  class="mdl-textfield__input">
              <label class="mdl-textfield__label" for="id_password">비밀번호</label>
              <input type="hidden" name="next" value="{{ next }}" />
            </div>

          </div>
        </div>
        <div class="mdl-card__actions mdl-card--border">
          <button class="mdl-button mdl-js-button vocat-color--primary" type="submit" style="float:right;">
            로그인하기
          </button>
        </div>
        <div class="mdl-card__menu">
          <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect">
            <i class="material-icons">share</i>
          </button>
          <div class="fb-like" data-href="https://www.facebook.com/vocatapp/" data-layout="button_count" data-action="like" data-show-faces="false" data-share="false"></div>
        </div>
      </div>
    </form>
  </div>

  <script type="text/javascript">
    document.getElementById('id_username').focus()
  </script>
{% endblock %}

vocat/accounts/templates/accounts/password_change_done.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block title %}{{ title }}{% endblock %}

{% block css %}
{% endblock %}

{% block head %}
{% endblock %}

{% block body %}
    {% url 'django-admindocs-docroot' as docsroot %}{% if docsroot %}<a href="{{ docsroot }}">{% trans 'Documentation' %}</a> / {% endif %}{% trans 'Change password' %} / <a href="{% url 'accounts:logout' %}">{% trans 'Log out' %}</a>

    <div class="breadcrumbs">
    <a href="{% url 'accounts:home' %}">{% trans 'Home' %}</a>
    &rsaquo; {% trans 'Password change' %}
    </div>
    <h1>{{ title }}</h1>
    <p>{% trans 'Your password was changed.' %}</p>
{% endblock %}

vocat/accounts/templates/accounts/password_change_form.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n admin_static %}

{% block title %}{{ title }}{% endblock %}

{% block css %}
{% endblock %}

{% block head %}
{% endblock %}

{% block body %}
    <p>this is accounts/password_change_form.html</p>

    {% url 'django-admindocs-docroot' as docsroot %}{% if docsroot %}<a href="{{ docsroot }}">{% trans 'Documentation' %}</a> / {% endif %} {% trans 'Change password' %} / <a href="{% url 'accounts:logout' %}">{% trans 'Log out' %}</a>

    <div class="breadcrumbs">
    <a href="{% url 'accounts:home' %}">{% trans 'Home' %}</a>
    &rsaquo; {% trans 'Password change' %}
    </div>

    <h1>{{ title }}</h1>

    <div id="content-main">
        <form method="post">{% csrf_token %}
        <div>
        {% if form.errors %}
            <p class="errornote">
            {% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
            </p>
        {% endif %}

        <p>{% trans "Please enter your old password, for security's sake, and then enter your new password twice so we can verify you typed it in correctly." %}</p>

        <fieldset class="module aligned wide">

        <div class="form-row">
            {{ form.old_password.errors }}
            {{ form.old_password.label_tag }} {{ form.old_password }}
        </div>

        <div class="form-row">
            {{ form.new_password1.errors }}
            {{ form.new_password1.label_tag }} {{ form.new_password1 }}
            {% if form.new_password1.help_text %}
            <p class="help">{{ form.new_password1.help_text|safe }}</p>
            {% endif %}
        </div>

        <div class="form-row">
        {{ form.new_password2.errors }}
            {{ form.new_password2.label_tag }} {{ form.new_password2 }}
            {% if form.new_password2.help_text %}
            <p class="help">{{ form.new_password2.help_text|safe }}</p>
            {% endif %}
        </div>

        </fieldset>

        <div class="submit-row">
            <input type="submit" value="{% trans 'Change my password' %}" class="default" />
        </div>

        <script type="text/javascript">document.getElementById("id_old_password").focus();</script>
        </div>
        </form>
    </div>
{% endblock %}

{% block js %}
{% endblock %}

vocat/accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{{ title }}{% endblock %}

{% block css %}
{% endblock %}

{% block head %}
{% endblock %}

{% block body %}
    <p>this is accounts/password_reset_complete.html</p>

    <div class="breadcrumbs">
    <a href="{% url 'accounts:home' %}">{% trans 'Home' %}</a>
    &rsaquo; {% trans 'Password reset' %}
    </div>

    <h1>{{ title }}</h1>

    <p>{% trans "Your password has been set.  You may go ahead and log in now." %}</p>
    <p><a href="{{ login_url }}">{% trans 'Log in' %}</a></p>
{% endblock %}

vocat/accounts/templates/accounts/password_reset_form.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block title %}{{ title }}{% endblock %}

{% block css %}
{% endblock %}

{% block head %}
{% endblock %}

{% block body %}
    <p>this is accounts/password_reset_form.html</p>

    <div class="breadcrumbs">
    <a href="{% url 'accounts:home' %}">{% trans 'Home' %}</a>
    &rsaquo; {% trans 'Password reset' %}
    </div>

    <h1>{{ title }}</h1>

    <p>{% trans "Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one." %}</p>

    <form method="post">{% csrf_token %}
    {{ form.email.errors }}
    <p><label for="id_email">{% trans 'Email address:' %}</label> {{ form.email }} <input type="submit" value="{% trans 'Reset my password' %}" /></p>
    </form>
{% endblock %}

vocat/accounts/templates/accounts/profile_change.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block title %}{{ title }}{% endblock %}

{% block css %}
{% endblock %}

{% block head %}
{% endblock %}

{% block body %}
    <p>this is accounts/profile_detail.html</p>

    {% url 'django-admindocs-docroot' as docsroot %}{% if docsroot %}<a href="{{ docsroot }}">{% trans 'Documentation' %}</a> / {% endif %} {% trans 'Change password' %} / <a href="{% url 'accounts:logout' %}">{% trans 'Log out' %}</a>

    <div class="breadcrumbs">
    <a href="{% url 'accounts:home' %}">{% trans 'Home' %}</a>
    &rsaquo; {% trans 'Profile Change' %}
    </div>

    <h1>{{ title }}</h1>

    <div id="content-main">
        <form method="post">{% csrf_token %}
        <div>
        {% if form.errors %}
            <p class="errornote">
            {% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
            </p>
            {{ form.errors }}
        {% endif %}

        <p>{% trans "Please fill out the form to change the profile." %}</p>

        <fieldset class="module aligned wide">
            {{ form.as_p }}
        </fieldset>

        <div class="submit-row">
            <input type="submit" value="{% trans 'Change Profile' %}" class="default" />
        </div>

        </div>
        </form>
    </div>

    <div class="profile-link">
        <a href="{% url 'accounts:profile_detail' %}">{% trans 'Back to Profile' %}</a>
    </div>

{% endblock %}

vocat/accounts/templates/accounts/profile_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block title %}{{ title }}{% endblock %}

{% block css %}
{% endblock %}

{% block head %}
{% endblock %}

{% block body %}
    <p>this is accounts/profile_detail.html</p>

    {% url 'django-admindocs-docroot' as docsroot %}{% if docsroot %}<a href="{{ docsroot }}">{% trans 'Documentation' %}</a> / {% endif %} {% trans 'Change password' %} / <a href="{% url 'accounts:logout' %}">{% trans 'Log out' %}</a>

    <div class="breadcrumbs">
    <a href="{% url 'accounts:home' %}">{% trans 'Home' %}</a>
    &rsaquo; {% trans 'Profile' %}
    </div>

    <h1>{{ title }}</h1>

    {{ data }}
    <br>
    {% for field, value in data.items %}
        <p>{{ field }} = {{ value }}</p>
    {% endfor %}

    <div class="profile-change-link">
        <a href="{% url 'accounts:profile_change' %}">{% trans 'Want to Change Profile?' %}</a>
    </div>

{% endblock %}

vocat/accounts/templates/accounts/registration_done.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block title %}{{ title }}{% endblock %}

{% block css %}
{% endblock %}

{% block head %}
{% endblock %}

{% block body %}
    {% url 'django-admindocs-docroot' as docsroot %}{% if docsroot %}<a href="{{ docsroot }}">{% trans 'Documentation' %}</a> / {% endif %}{% trans 'Change password' %} / <a href="{% url 'accounts:login' %}">{% trans 'Log in' %}</a>

    <div class="breadcrumbs">
    <a href="{% url 'accounts:home' %}">{% trans 'Home' %}</a>
    &rsaquo; {% trans 'Registration' %}
    </div>
    <h1>{{ title }}</h1>
    <p>{% trans 'Thank you for joining Vocat. Your account has been registratered.' %}</p>
    <div class="login-link">
        <a href="{% url 'accounts:login' %}">{% trans 'Now, you may login.' %}</a>
    </div>
{% endblock %}

vocat/accounts/templates/accounts/registration_form.html
{% extends 'base_home.html' %}
{% load staticfiles %}
{% load i18n admin_static %}
{% block title %}회원가입{% endblock %}


{% block content %}
  <!-- Wide card with share menu button -->
  <style>
    .demo-card-wide.mdl-card {
      width: 100%;
    }
    .demo-card-wide > .mdl-card__title {
      color: #000;
      height: 60px;
      border-bottom: 1px solid #e5e5e5;
    }
    .demo-card-wide > .mdl-card__menu {
      color: #fff;
    }
  </style>

  <div style="max-width:400px; margin:0 auto; padding:60px 10px;">
    <form method="post">{% csrf_token %}
      <div class="demo-card-wide mdl-card mdl-shadow--2dp">
        <div class="mdl-card__title">
          <h2 class="mdl-card__title-text">회원가입</h2>
        </div>
        <div class="mdl-card__supporting-text" style="text-align:center;">
          {% if form.errors %}
            <p class="errornote">
              {% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
            </p>
            {{ form.errors }}
          {% endif %}

          <div id="tt1">
            <a href="{% url 'accounts:login' %}" style="color:gray;">이미 보캣 회원이신가요?</a>
          </div>
          <div class="mdl-tooltip" for="tt1">
            로그인하기
          </div>
          <div id="content-main">
            {% if user.is_authenticated %}
              <p class="errornote">
                {% blocktrans trimmed with username=request.user.username %}
                  You are authenticated as {{ username }}, but are not authorized to
                  access this page. Would you like to login to a different account?
                {% endblocktrans %}
              </p>
            {% endif %}

            {{ form.email.errors }}
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
              <input id="id_email" maxlength="254" name="email" type="email" class="mdl-textfield__input">
              <label class="mdl-textfield__label" for="id_email">이메일 주소</label>
            </div>
            {{ form.password1.errors }}
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
              <input id="id_password1" pattern=".{0}|.{8,}" title="최소 8 글자" name="password1" type="password"  class="mdl-textfield__input">
              <label class="mdl-textfield__label" for="id_password1">비밀번호</label>
            </div>
            {{ form.password2.errors }}
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
              <input id="id_password2" pattern=".{0}|.{8,}" title="최소 8 글자" name="password2" type="password"  class="mdl-textfield__input">
              <label class="mdl-textfield__label" for="id_password2">비밀번호 한 번 더</label>
            </div>
            {{ form.name.errors }}
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
              <input id="id_name" maxlength="70" name="name" type="text"  class="mdl-textfield__input">
              <label class="mdl-textfield__label" for="id_name">이름</label>
              <input type="hidden" name="next" value="{{ next }}" />
            </div>
          </div>
        </div>
        <div class="mdl-card__actions mdl-card--border">
          <button class="mdl-button mdl-js-button vocat-color--primary" type="submit" style="float:right;">
            가입하기
          </button>
        </div>
        <div class="mdl-card__menu">
          <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect">
            <i class="material-icons">share</i>
          </button>
          <div class="fb-like" data-href="https://www.facebook.com/vocatapp/" data-layout="button_count" data-action="like" data-show-faces="false" data-share="false"></div>
        </div>
      </div>
    </form>
  </div>
  <script type="text/javascript">
    document.getElementById('id_email').focus()
  </script>
{% endblock %}